#!/usr/bin/env python3
"""Merge the two source bibliographies into EH_Book/references.bib.

Sources
    ../EH_shallow/references.bib      37 entries, 35 carrying a doi field
    ../sources/GWL/bibfile.bib       106 entries

Six keys appear in both files. The habitability manuscript version wins on a
clash, because that is the version whose formatting the book's citation style
was matched against. A clash is only reported, never silently resolved, so a
genuine divergence in the underlying reference is visible.

Run from EH_Book/:
    python3 tools/merge_bib.py
"""

import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
BOOK = os.path.dirname(HERE)
ROOT = os.path.dirname(BOOK)

# Order matters: the first source to define a key wins. The author supplied
# bibliography is listed first so it overrides both manuscript files.
SOURCES = [
    ("LATEST", os.path.join(BOOK, "references_latest.bib")),
    ("CRYO", os.path.join(BOOK, "references_cryosphere.bib")),
    ("EH", os.path.join(ROOT, "EH_shallow", "references.bib")),
    ("GWL", os.path.join(ROOT, "sources", "GWL", "bibfile.bib")),
]
CORRECTIONS = os.path.join(BOOK, "corrections.bib")

# Keys the author's latest bibliography deliberately dropped, which survive only
# in the older manuscript file, whose identifiers were verified to point at the
# wrong work, and which nothing in the book cites. Carrying them forward would
# reintroduce known bad references into the reference list.
RETIRED = {
    "bekaert2017centralvalley":
        "dropped from the author's latest file; doi resolved to an unrelated "
        "biomass paper and no work with this title exists in Crossref",
    "sneed2008extensometer":
        "dropped from the author's latest file and superseded by "
        "sneed2013deltamendota, sneed2018aqueduct and sneed2020coachella; "
        "doi resolved to a Kansas water quality report",
}
TARGET = os.path.join(BOOK, "references.bib")

ENTRY_START = re.compile(r"^@(\w+)\s*\{\s*([^,\s]+)\s*,", re.MULTILINE)


def parse(path):
    """Return [(key, entrytype, raw_text)] by walking balanced braces."""
    with open(path, encoding="utf-8") as fh:
        text = fh.read()

    entries = []
    for match in ENTRY_START.finditer(text):
        etype, key = match.group(1).lower(), match.group(2)
        if etype in ("comment", "preamble", "string"):
            continue
        start = match.start()
        depth = 0
        end = None
        for i in range(text.index("{", start), len(text)):
            if text[i] == "{":
                depth += 1
            elif text[i] == "}":
                depth -= 1
                if depth == 0:
                    end = i + 1
                    break
        if end is None:
            print("unbalanced braces at key %s in %s" % (key, path), file=sys.stderr)
            return []
        entries.append((key, etype, text[start:end].rstrip()))
    return entries


def has_doi(raw):
    return re.search(r"^\s*doi\s*=", raw, re.MULTILINE | re.IGNORECASE) is not None


def main():
    merged = {}
    order = []
    origin = {}
    clashes = []
    retired_seen = set()

    for label, path in SOURCES:
        if not os.path.exists(path):
            if label in ("LATEST", "CRYO"):
                print("%-6s (absent, skipping)" % label)
                continue
            print("missing source: %s" % path, file=sys.stderr)
            return 1
        found = parse(path)
        print("%-6s %3d entries  %s" % (label, len(found), os.path.relpath(path, ROOT)))
        for key, etype, raw in found:
            if key in RETIRED:
                retired_seen.add(key)
                continue
            if key in merged:
                clashes.append((key, origin[key], label))
                continue
            merged[key] = raw
            origin[key] = label
            order.append(key)

    order.sort(key=str.lower)

    # Overlay: a corrected entry replaces the merged one for the same key.
    fixed = []
    if os.path.exists(CORRECTIONS):
        for key, etype, raw in parse(CORRECTIONS):
            if key in merged:
                merged[key] = raw
                fixed.append(key)
            else:
                merged[key] = raw
                order.append(key)
                fixed.append(key + " (new)")
        order.sort(key=str.lower)

    with open(TARGET, "w", encoding="utf-8") as fh:
        fh.write(
            "% ==========================================================\n"
            "%  references.bib for Earth Habitability\n"
            "%\n"
            "%  Generated by tools/merge_bib.py. Do not edit by hand:\n"
            "%  edit the source .bib files and regenerate, or the next run\n"
            "%  will discard the change.\n"
            "%\n"
            "%  The doi field on each entry is what produces the live link\n"
            "%  in the printed reference list, through the \\doi override\n"
            "%  defined in springerbook.sty.\n"
            "% ==========================================================\n\n"
        )
        for key in order:
            fh.write(merged[key])
            fh.write("\n\n")

    withdoi = sum(1 for k in order if has_doi(merged[k]))
    print("")
    print("merged      %3d unique entries" % len(order))
    print("with doi    %3d (%d without, expected for pre digital era works)"
          % (withdoi, len(order) - withdoi))
    if retired_seen:
        print("")
        print("RETIRED     %3d superseded entries dropped:" % len(retired_seen))
        for key in sorted(retired_seen):
            print("   %-30s %s" % (key, RETIRED[key]))
    print("")
    print("corrected   %3d entries from corrections.bib: %s" % (len(fixed), ", ".join(fixed) if fixed else "none"))
    print("clashes     %3d" % len(clashes))
    for key, kept, dropped in clashes:
        print("   %-30s kept %-6s dropped %s" % (key, kept, dropped))
    print("")
    print("written to  %s" % os.path.relpath(TARGET, ROOT))
    return 0


if __name__ == "__main__":
    sys.exit(main())
